insert into kategorie (kat_id, kat_nazwa) values (1, 'owoce');
insert into kategorie (kat_id, kat_nazwa) values (2, 'warzywa');

insert into (t_id, t_nazwa, t_link, t_kat_id) values (  1, 'abiu', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values (  2, 'abio', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values (  3, 'agrest', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values (  4, 'amla', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values (  5, 'ananas', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values (  6, 'arbuz', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values (  7, 'aronia', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values (  8, 'awokado', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values (  9, 'banan', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 10, 'biała porzeczka', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 11, 'borówka', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 12, 'brusznica', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 13, 'borówka amerykańska', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 14, 'brzoskwinia', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 15, 'buk', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 16, 'cytryna', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 17, 'czarna porzeczka', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 18, 'czarny bez', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 19, 'czeremcha', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 20, 'czereśnia', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 21, 'czerwona porzeczka', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 22, 'daktyl', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 23, 'dereń', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 24, 'durian', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 25, 'dzika róża', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 26, 'figa', '', 1);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 27, 'bakłażan', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 28, 'oberżyna', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 29, 'batat', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 30, 'patat', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 31, 'botwina', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 32, 'bobik', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 33, 'bób', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 34, 'brokuł', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 35, 'brukiew', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 36, 'brukselka ', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 37, 'burak', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 38, 'cebula', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 39, 'chrzan', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 40, 'ciecierzyca', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 41, 'groch włoski', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 42, 'cukinia', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 43, 'kabaczek', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 44, 'cykoria', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 45, 'czosnek', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 46, 'czyściec', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 47, 'dynia', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 48, 'endywia', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 49, 'fasola', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 50, 'fasolka szparagowa', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 51, 'fenkuł', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 52, 'koper włoski', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 53, 'groch', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 54, 'groch włoski', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 55, 'ignam', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 56, 'jarmuż', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 57, 'kabaczek', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 58, 'kalafior', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 59, 'kalarepa', '', 2);
insert into (t_id, t_nazwa, t_link, t_kat_id) values ( 60, 'kapar', '', 2);
